name: NDAify CD

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'master'
      # Install node
      - uses: actions/setup-node@v1
        with:
          node-version: '14.2.0'
      # Utilize yarn cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # Install deps
      - run: yarn install --frozen-lockfile
      # Run tests
      - run: yarn test

  i18n-ready: 
    name: Check i18n
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Bail if language tokens are missing
        run: |
          # TODO bail if i18n is not ready 
          sleep 1
          exit 1

  deploy:
    name: Deploy
    needs: i18n-ready
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'master'
      # Run `flyctl deploy`.
      - uses: superfly/flyctl-actions@master
        with:
          args: "deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}